# Generated by Django 2.2.6 on 2021-06-04 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
